### ISSUE TITLE
No Phidgets - Not working

### ISSUE THREAD

**Issue by padibona** [lucapinello/SR700_Artisan_Server#1]
Hey,

I installed things but I get an error that makes me think the phidgets is still attempting to connect (even though I used the no_phidget option.

I installed the phidgets driver otherwise I was getting other errors. Anyways after installing the phidgets driver and starting via the Start_SR700_Artisan_Server no_phidget command I get the following error:

Opening and Waiting for Attachment...
Runtime Error -> Opening Phidget Channel:
        Desc: Timed Out

This error commonly occurs if your device is not connected as specified, or if another program is using the device, such as the Phidget Control Panel.

If your Phidget has a plug or terminal block for external power, ensure it is plugged in and powered.

If you are trying to connect to an analog sensor, you will need to use the corresponding VoltageInput or VoltageRatioInput API with the appropriate SensorType.
Process Process-1:
Traceback (most recent call last):
  File "c:\users\pete\appdata\local\programs\python\python36\lib\site-packages\freshroastsr700_phidget\__init__.py", line 31, in __init__
    self.ch.openWaitForAttachment(5000)
  File "c:\users\pete\appdata\local\programs\python\python36\lib\site-packages\Phidget22\Phidget.py", line 646, in openWaitForAttachment
    raise PhidgetException(result)
Phidget22.PhidgetException.PhidgetException: 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\pete\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\pete\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\pete\appdata\local\programs\python\python36\lib\site-packages\freshroastsr700_phidget\__init__.py", line 121, in _comm
    ph=PhidgetTemperature()
  File "c:\users\pete\appdata\local\programs\python\python36\lib\site-packages\freshroastsr700_phidget\__init__.py", line 34, in __init__
    raise EndProgramSignal("Program Terminated: Open Failed")
freshroastsr700_phidget.PhidgetHelperFunctions.EndProgramSignal: Program Terminated: Open Failed

Any ideas? 

I am Python familiar and own a Mastech MS6514 and am willing to take a crack at getting that integtrated if you don't own one. 

Anyways, looking forward to get things up and running.

Thanks,

Pete

**Comment by lucapinello** [comment]
Hey Pete,

Thanks for reporting this, I think I know how to fix this problem.

To get the integration with Mastech essentially you need to write a small class with 3 simple methods :

initialize the device
read the temperature
close the connection with the device

See what I did here for the Phidget:

https://github.com/lucapinello/freshroastsr700_phidget/blob/8834665d9514284db9b1cbc03bb9ad4ab093eeff/freshroastsr700_phidget/__init__.py#L17

If you write this minimal class I can integrate it on the current server.

**Comment by padibona** [comment]
Interesting, I looked around in Artisan folder in Windows and it looks like I had a folder under C:\Program Files\Artisan\SR700 which I don't think came from your install correct? I at one point did play with the OG infinigrove code and that may explain why that folder is there. Let me try a couple things :).

**Comment by lucapinello** [comment]
Hi @padibona you may need to check where the setup stores the scripts on windows. Look for the folder where you have Start_SR700_Artisan_Server.exe

This folder should be in your PATH

If not you can just change the setting of Artisan and add the full path for each of the required scripts in  under Config/events in artisan

**Comment by lucapinello** [comment]
I tested the current setup with Windows and Python Anaconda3 and it works. It seems you have a different Python version.
