### ISSUE TITLE
Cannot make roaster connection when using phidget flag

### ISSUE THREAD

**Issue by stackptr** [lucapinello/SR700_Artisan_Server#2]
On macOS Mojave, having installed OpenRoast 1.2.0rc3, which connects just fine. I have a Phidget setup with thermocouple and VINT hub and can read the temperature via the Phidget Control Panel.

Since I have the VINT hub I assume I should be using `--enable_extension phidget_hub`. However, when I use either phidget flag, I get the same looping status message:

```
-[ Still waiting for connection... ]-
-[ Please check if the roaster is connected. ]-
```

I setup a test python script using the `freshroastsr700` repo and from that I can get a basic connection:

```python
import freshroastsr700

roaster = freshroastsr700.freshroastsr700()

roaster.connected # == 0

roaster.connect()

roaster.connected # == 1
```

Additionally, running with no flags seems to give the expected looping messages, but without the Phidget connection that I'm trying to get:

```
-[ Server Ready! ]-
-[ [State:idle](Temp SR700:150)(Target temp: 150)(Fan Speed: 1)(Time left: 0) ]-
-[ [State:idle](Temp SR700:150)(Target temp: 150)(Fan Speed: 1)(Time left: 0) ]-
-[ [State:idle](Temp SR700:150)(Target temp: 150)(Fan Speed: 1)(Time left: 0) ]-
```

So it seems likely that might problem might be related to how the `roaster` object is configured, but I haven't had the chance to poke around with different options. Any thoughts on further debugging?

**Comment by lucapinello** [comment]
Thanks for the feedback, can you try to do:
pip install SR700_Artisan_Server==0.8

Then start the server with Start_SR700_Artisan_Server --enable_extension phidget_hub  --phidget_hub_port 0 --phidget_hub_channel 1

You may need to adjust hub port and channel with your setup

**Comment by stackptr** [comment]
I was messing around with this script which connects with hub at 0, channel at 0:

```python
from freshroastsr700_phidget import SR700Phidget

roaster = SR700Phidget(
    use_phidget_temp=True,
    phidget_use_hub=True,
    phidget_hub_port=0,
    phidget_hub_channel=0,
)

roaster.connect()

print(roaster.connected) # prints 1
```

Other arguments, such as when I set `phidget_hub_port=1` yielded some useful debugging info:

```
Runtime Error -> Opening Phidget Channel: 
	Desc: Timed Out

This error commonly occurs if your device is not connected as specified, or if another program is using the device, such as the Phidget Control Panel.

If your Phidget has a plug or terminal block for external power, ensure it is plugged in and powered.

If you are trying to connect to an analog sensor, you will need to use the corresponding VoltageInput or VoltageRatioInput API with the appropriate SensorType.
ERROR:root:Phidget: I cannot communicate with the Phidget device.
ERROR:root:Phidget: Try to reboot your machine and try again.
```

However, using port 0 and channel 0 still yields the same logging info, waiting for connection to the roaster.

**Comment by stackptr** [comment]
That same script above with `roaster.connect()` replaced with `roaster.auto_connect()`yields a `0` indicating it wasn't able to connect, so maybe this is the difficulty?

**Comment by lucapinello** [comment]
Hey just found a solution for this! Please update to the latest version 0.9

pip install SR700_Artisan_Server==0.9

Then 

Start_SR700_Artisan_Server --enable_extension phidget_hub --phidget_hub_port 0 --phidget_hub_channel 1

**Comment by stackptr** [comment]
Replacing that call in `Start_SR700_Artisan_Server.py` and running with `python2.7 SR700_Artisan_Server/Start_SR700_Artisan_Server.py --enable_extension phidget_hub --phidget_hub_port 0 --phidget_hub_channel 0` never gets past the connection loop, but also doesn't state that it cannot find the roaster connection. I'm probably doing something wrong with trying to run the script from the cloned repo versus the `pip` install. Any advice there?

**Comment by lucapinello** [comment]
Yes you need to use pip and the legacy code I changed other things there.

**Comment by stackptr** [comment]
Ok so I looked at the last several commits and have tried doing the following:

- Upgraded to 1.0
- Run `Start_SR700_Artisan_Server --enable_extension phidget_hub --phidget_hub_port 0 --phidget_hub_channel 0` (tried channels 0 and 1 for completeness)
- Run `/Applications/Artisan.app/Contents/MacOS/Artisan` from another Terminal window

I am still getting the connecting loop. Is there any other step I am missing?

I tried reloading the settings file into Artisan to see if that helped things. I notice it sets the ET/BT Device to an external program, `Get_Artisan_and_Phidget_Temp` -- if I run that from Terminal I get the following error, though it could be because I'm lacking other scaffolding. Does this look like it could cause the lack of connection?

```
Get_Artisan_and_Phidget_Temp
Traceback (most recent call last):
  File "/usr/local/bin/Get_Artisan_and_Phidget_Temp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/SR700_Artisan_Server/Get_Artisan_and_Phidget_Temp.py", line 9, in main
    et,bt=roast_control.output_sr700_and_phidget_temp()
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 275, in __getattr__
    self._pyroGetMetadata()
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 615, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 588, in __pyroCreateConnection
    uri = _resolve(self._pyroUri, self._pyroHmacKey)
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 1911, in _resolve
    return nameserver.lookup(uri.object)
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/Pyro4/core.py", line 476, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
Pyro4.errors.NamingError: unknown name: roaster.sr700
```

**Comment by lucapinello** [comment]
Try to turn off the roster and your pc. Turn on the roaster then start your
pc. After that start right away the server. Also is openroast working fine
for you all the times? On my Mac the sr700 is not very stable and I get a
good connection only after a reboot.

**Comment by stackptr** [comment]
OpenRoast is working fine for me. I have not used Artisan before this.

How can I build this locally so that I can play around on my own? I'm unfamiliar with Python tooling but I feel like that is the major hurdle for figuring this out

**Comment by lucapinello** [comment]
Thanks for sharing this!
