### ISSUE TITLE
Roast dropped prior to FCs

### ISSUE THREAD

**Issue by stackptr** [lucapinello/SR700_Artisan_Server#3]
I was able to test this server with some green coffee and had the following results:

![test](https://user-images.githubusercontent.com/4542907/52393034-3cadf480-2a59-11e9-81ef-ee973c9fd16b.png)

The cooling phase started before my roast reached first crack.

I haven't used Artisan prior to getting this up and running, so I feel like I may have some stuff to learn, but my general understanding was that I would be able to run this server (acting as the middle man between controlling the SR700 and obtaining temperature readings from the Phidgets) and use Artisan to mark each stage of the roast, before dropping. I assumed that I would have the ability to control when the cooling phase started, but this seemed to happen automatically.

Have I made some rookie mistake or is it possible I set this up wrong? I have a single probe in the top of the roaster to serve as BT, and I'm guessing ET is simply the roaster's own reading.

**Comment by stackptr** [comment]
Other notes:

-  The DE event was also marked automatically, though around where I was anticipating it so I figure that happened based on a temperature reading
- I have read the quick start guide for Artisan and my laptop is on battery

**Comment by lucapinello** [comment]
Hi Corey this is working as designed so the server is now working for you.
The machine is running based on the instructions in the alarms section. You
can create new profiles using the other software linked at the end of the
page. Take also a look to the artisan manual.

**Comment by stackptr** [comment]
@lucapinello that makes sense, I see the alarms that were loaded in, probably from the settings file. Is there any reason this is considered a "generic profile"? It seems to me that this would vary based on the green coffee used, or from roaster to roaster (as apparently some SR700s run "cooler").

For now I will clear the alarms since I believe this will get me into the more manual state that i'm wanting to achieve. Then after I get a solid roast I can construct an alarm profile from it that could replicate it for future iterations.

Thanks for the continued support!

**Comment by stackptr** [comment]
I see that these alarms seem to control the temperature and fan through the roast. I had thought the server software was acting as a PID controller for the BT and controlling the roaster accordingly. Is this mistaken? If I remove or disable these alarms, will it result in a constant and unvarying control?

**Comment by lucapinello** [comment]
Yes, in this new version I have also  config that will create some special buttons to disable the automatic control of fan and temperature based on the alarms at any moment during the roasting.
