### ISSUE TITLE
Not able to start roast

### ISSUE THREAD

**Issue by jacobcvt12** [lucapinello/SR700_Artisan_Server#6]
Thanks for building this software.

I'm trying to start a roast. I've done the following:

1. install the software inside of a conda env
2. activated the environment
3. plugged in my roaster
4. run `Start_SR700_Artisan_Server` (and noted that a connection has been established)
5. opened artisan
6. clicked the large "Start" button in artisan

I get the following error:

```
Exception: callprogram() [Errno 2] No such file or directory: ‘Get_Artisan_Temps’: 'Get_Artisan_Temps' @line 39035
```

Am I doing something wrong?

**Comment by lucapinello** [comment]
Hey Jacob, it depends on the OS you are using.

This error suggests that you are starting artisan from another env so it cannot find the programs installed in the conda env by the server.

Anyway, there are two easy way to fix this. 

1) Start Artisan within the conda env you have created so it will find the required commands

2) You can specify the full path of the commands under Artisan-> Config -> Events Buttons and Quantifiers.

**Comment by jacobcvt12** [comment]
Thanks @lucapinello ! I will give this a try.
